### ISSUE TITLE
github.com/osrg/gobgp/packet cannot find package

### ISSUE THREAD

**Issue by tiatam010** [woanware/bgp-watcher#2]
New to Golang here, I got an error and hope you maybe able to assist. 
`package github.com/osrg/gobgp/packet: cannot find package "github.com/osrg/gobgp/packet" in any of: ...`

Looking into the dependency project, it seems that the path has changed.

**Comment by woanware** [comment]
All of the dependency code should all be there, under the "vendor" directory? So it should build OK with the code in the repo?

**Comment by tiatam010** [comment]
Got it, thank you for the quick reply.

**Comment by woanware** [comment]
There is definitely an issue with the library path now, so thanks for
highlighting it. Will try and get it resolved for future updates
